apiVersion: v1
kind: Service # Services: Sets up networking in a Kubernetes Cluster
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 3000
      nodePort: 31515
  selector:
    component: web
